version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      actions-toolkit:
        patterns:
          - '@actions/*'
      dev-tooling:
        patterns:
          - 'typescript'
          - 'esbuild'
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'prettier'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
