// Docker OCI publishing (M6.3).
//
// Builds a minimal OCI image per linux-* target that simply COPYs the pkg
// binary into /usr/local/bin and sets it as ENTRYPOINT, then pushes one
// single-arch image per target and (when >1 arch is built) a manifest list
// combining them under the canonical image ref.
//
// No Docker SDK dep — everything shells out through the existing ExecFn, so
// tests can verify argv/env shape without touching a real Docker daemon.
// Registry credentials never appear on argv: we write a config.json into a
// private DOCKER_CONFIG directory with base64-encoded auths and hand that
// directory to buildx via env. Secrets registered with core.setSecret are
// never re-embedded in a log line.

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { UploadError } from './errors.ts';
import type { Logger } from './logger.ts';
import type { ExecFn } from './pkg-runner.ts';

// ─── Types ────────────────────────────────────────────────────────────────

export interface DockerInputs {
  /** Image reference, e.g. `ghcr.io/org/app:{version}`. Supports the same tokens
   *  as the filename template — substituted by the orchestrator before publish. */
  readonly image: string;
  /** Registry host (e.g. `ghcr.io`). Derived from the image ref when unset. */
  readonly registry: string | undefined;
  /** Secret. Registered via core.setSecret by the parser. */
  readonly username: string | undefined;
  /** Secret. Registered via core.setSecret by the parser. */
  readonly password: string | undefined;
  /** Base image the generated Dockerfile FROMs. Defaults to distroless/base. */
  readonly baseImage: string;
  /** When set, skip the generated Dockerfile and point buildx at this one. */
  readonly dockerfile: string | undefined;
}

export interface DockerPushTarget {
  /** pkg os — must be a linux variant. */
  readonly os: 'linux' | 'linuxstatic' | 'alpine';
  readonly arch: string;
  readonly binaryPath: string;
  readonly binaryName: string;
}

export interface DockerPushRequest {
  /** Fully-rendered image ref (tokens already substituted). Must include a tag. */
  readonly image: string;
  readonly registry: string;
  readonly username: string | undefined;
  readonly password: string | undefined;
  readonly baseImage: string;
  readonly dockerfile: string | undefined;
  readonly targets: readonly DockerPushTarget[];
  readonly tempDir: string;
  readonly binaryName: string;
}

export interface DockerPushResult {
  /** Every image reference produced — per-arch refs + the manifest ref when >1. */
  readonly images: readonly string[];
  /** Canonical manifest-list ref. undefined when only one arch was pushed. */
  readonly manifestRef: string | undefined;
}

export interface DockerPublisher {
  publish(req: DockerPushRequest): Promise<DockerPushResult>;
}

// ─── Pure helpers ─────────────────────────────────────────────────────────

/** Render the generated Dockerfile. */
export function renderDockerfile(binaryName: string, baseImage: string): string {
  if (binaryName === '' || /\s/.test(binaryName)) {
    throw new UploadError(`Invalid binary name for Dockerfile: ${JSON.stringify(binaryName)}`);
  }
  const lines = [
    `# Generated by yao-pkg/pkg-action — do not edit by hand.`,
    `FROM ${baseImage}`,
    `COPY ${binaryName} /usr/local/bin/${binaryName}`,
    `ENTRYPOINT ["/usr/local/bin/${binaryName}"]`,
    ``,
  ];
  return lines.join('\n');
}

/** Map a pkg target to the `linux/<docker-arch>` platform string. */
export function targetToDockerPlatform(target: {
  readonly os: string;
  readonly arch: string;
}): string {
  if (target.os !== 'linux' && target.os !== 'linuxstatic' && target.os !== 'alpine') {
    throw new UploadError(`Docker publish only supports linux-* targets; got ${target.os}`);
  }
  const arch = target.arch;
  if (arch === 'x64') return 'linux/amd64';
  if (arch === 'arm64') return 'linux/arm64';
  if (arch === 'armv7') return 'linux/arm/v7';
  if (arch === 'armv6') return 'linux/arm/v6';
  if (arch === 'ppc64') return 'linux/ppc64le';
  if (arch === 's390x') return 'linux/s390x';
  throw new UploadError(`Docker publish has no platform mapping for arch "${arch}"`);
}

/** Extract the registry host from an image ref. Falls back to Docker Hub. */
export function extractRegistry(imageRef: string): string {
  const firstSlash = imageRef.indexOf('/');
  if (firstSlash === -1) return 'docker.io';
  const head = imageRef.slice(0, firstSlash);
  // Heuristic: a registry host must contain either "." or ":" (port) or be
  // "localhost". Otherwise it's a Docker Hub namespace.
  if (head === 'localhost' || head.includes('.') || head.includes(':')) return head;
  return 'docker.io';
}

/** Derive a per-arch image tag like `ghcr.io/org/app:1.0.0-amd64`. */
export function archTag(imageRef: string, platform: string): string {
  const archSuffix = platform.replace(/^linux\//, '').replace(/\//g, '-');
  return `${imageRef}-${archSuffix}`;
}

/** Build the Docker auths config blob. Base64-encodes `user:pass`. */
export function buildDockerAuthsConfig(
  registry: string,
  username: string,
  password: string,
): string {
  const auth = Buffer.from(`${username}:${password}`, 'utf8').toString('base64');
  return JSON.stringify({ auths: { [registry]: { auth } } }, null, 2);
}

// ─── Production publisher ─────────────────────────────────────────────────

export interface DockerPublisherDeps {
  readonly exec: ExecFn;
  readonly logger: Logger;
}

/**
 * Shell-out-based publisher. Assumes `docker` (with buildx) is on PATH — true
 * for ubuntu-latest GitHub runners. Registry auth is handed over via a
 * scoped DOCKER_CONFIG dir; nothing secret rides argv.
 */
export function createDefaultDockerPublisher(deps: DockerPublisherDeps): DockerPublisher {
  return {
    async publish(req: DockerPushRequest): Promise<DockerPushResult> {
      if (req.targets.length === 0) {
        throw new UploadError('Docker publish requires at least one linux-* target.');
      }

      // 1. Prepare a private DOCKER_CONFIG directory when creds are supplied.
      const configDir = join(req.tempDir, 'docker-config');
      const dockerEnv: Record<string, string> = { DOCKER_CONFIG: configDir };
      if (req.username !== undefined && req.password !== undefined) {
        await mkdir(configDir, { recursive: true, mode: 0o700 });
        const body = buildDockerAuthsConfig(req.registry, req.username, req.password);
        await writeFile(join(configDir, 'config.json'), body, { mode: 0o600 });
      } else {
        // Still create the dir so DOCKER_CONFIG points at a usable location,
        // and buildx doesn't fall back to the runner-wide config.
        await mkdir(configDir, { recursive: true, mode: 0o700 });
      }

      // 2. Ensure the builder exists (buildx requires a builder for --push).
      //    `docker buildx create --use` is idempotent if the builder already
      //    exists under the same name. Use a stable, action-scoped name so
      //    concurrent runs don't stomp each other.
      await runExec(deps, 'docker', ['buildx', 'create', '--name', 'pkg-action', '--use'], {
        env: dockerEnv,
        ignoreReturnCode: true, // `already exists` returns 1
      });

      // 3. Per-target build + push.
      const pushedRefs: string[] = [];
      for (const target of req.targets) {
        const platform = targetToDockerPlatform(target);
        const tag = archTag(req.image, platform);
        const contextDir = join(req.tempDir, `docker-ctx-${target.arch}`);
        await mkdir(contextDir, { recursive: true });

        // Copy the binary into the build context with a stable name so the
        // generated Dockerfile's COPY line is predictable. Skip copy when the
        // user supplied their own Dockerfile — they own the layout.
        let dockerfilePath: string;
        if (req.dockerfile !== undefined) {
          dockerfilePath = req.dockerfile;
        } else {
          const { copyFile } = await import('node:fs/promises');
          await copyFile(target.binaryPath, join(contextDir, req.binaryName));
          dockerfilePath = join(contextDir, 'Dockerfile');
          await writeFile(dockerfilePath, renderDockerfile(req.binaryName, req.baseImage), {
            mode: 0o644,
          });
        }

        deps.logger.info(
          `[pkg-action] Docker: building ${tag} for ${platform} (binary: ${target.binaryPath}).`,
        );
        await runExec(
          deps,
          'docker',
          [
            'buildx',
            'build',
            '--platform',
            platform,
            '--push',
            '-t',
            tag,
            '-f',
            dockerfilePath,
            contextDir,
          ],
          { env: dockerEnv },
        );
        pushedRefs.push(tag);
      }

      // 4. Manifest list — only when >1 arch was pushed. Single-arch flows
      //    just tag that arch as the canonical ref via imagetools.
      let manifestRef: string | undefined;
      if (pushedRefs.length >= 2) {
        deps.logger.info(
          `[pkg-action] Docker: creating manifest list ${req.image} from ${String(pushedRefs.length)} arch ref(s).`,
        );
        await runExec(
          deps,
          'docker',
          ['buildx', 'imagetools', 'create', '--tag', req.image, ...pushedRefs],
          { env: dockerEnv },
        );
        manifestRef = req.image;
      } else if (pushedRefs.length === 1 && pushedRefs[0] !== req.image) {
        deps.logger.info(
          `[pkg-action] Docker: retagging ${pushedRefs[0] as string} as ${req.image}.`,
        );
        await runExec(
          deps,
          'docker',
          ['buildx', 'imagetools', 'create', '--tag', req.image, pushedRefs[0] as string],
          { env: dockerEnv },
        );
        manifestRef = req.image;
      }

      const images = manifestRef !== undefined ? [...pushedRefs, manifestRef] : [...pushedRefs];
      return { images, manifestRef };
    },
  };
}

async function runExec(
  deps: DockerPublisherDeps,
  command: string,
  args: readonly string[],
  options: { env?: Record<string, string>; ignoreReturnCode?: boolean } = {},
): Promise<void> {
  const opts: { env?: Record<string, string>; ignoreReturnCode?: boolean } = {};
  if (options.env !== undefined) opts.env = options.env;
  if (options.ignoreReturnCode !== undefined) opts.ignoreReturnCode = options.ignoreReturnCode;
  const result = await deps.exec(command, args, opts);
  if (result.exitCode !== 0 && options.ignoreReturnCode !== true) {
    throw new UploadError(
      `${command} ${args.join(' ')} exited ${String(result.exitCode)}: ${result.stderr || result.stdout}`,
    );
  }
}
