// Release-body markdown generator.
//
// Turns the SummaryRow + artifact list into a release body with a table of
// binaries, sizes (human-readable), and primary checksums. Kept as a pure
// module so tests can drive it without Octokit or fs.

import type { SummaryRow } from './summary.ts';

export interface ReleaseBodyInput {
  /** User-supplied body. When set, it precedes the generated table. */
  readonly userBody: string | undefined;
  readonly rows: readonly SummaryRow[];
  /** Action version string ("0.0.0") stamped into the trailer. */
  readonly actionVersion: string;
}

/** Assemble the release body. When there are no rows the user body is
 *  returned unchanged; when there are rows and no user body we emit just the
 *  table + trailer. */
export function buildReleaseBody(input: ReleaseBodyInput): string {
  const table = renderTable(input.rows);
  const trailer = `\n<sub>Generated by <code>yao-pkg/pkg-action@${input.actionVersion}</code>.</sub>\n`;
  if (table === '') {
    // No rows — preserve just the user body (plus trailer if user body is empty).
    if (input.userBody !== undefined && input.userBody.trim() !== '') return input.userBody;
    return trailer.trimStart();
  }
  const sections: string[] = [];
  if (input.userBody !== undefined && input.userBody.trim() !== '') {
    sections.push(input.userBody.trimEnd());
  }
  sections.push('## Binaries\n\n' + table);
  sections.push(trailer.trimStart());
  return sections.join('\n\n');
}

function renderTable(rows: readonly SummaryRow[]): string {
  if (rows.length === 0) return '';
  const header = '| Target | File | Size | Checksum |';
  const divider = '| --- | --- | --- | --- |';
  const lines: string[] = [header, divider];
  for (const row of rows) {
    const size = humanSize(row.sizeBytes);
    const digest =
      row.primaryDigest !== undefined
        ? `\`${row.primaryDigest.algo}:${shortenDigest(row.primaryDigest.value)}\``
        : '—';
    const filename = row.filename.split(/[\\/]/).pop() ?? row.filename;
    lines.push(`| \`${row.target}\` | \`${filename}\` | ${size} | ${digest} |`);
  }
  return lines.join('\n');
}

/** Human-readable file size. Returns a decimal-megabyte string — release
 *  tables read better than raw bytes. */
export function humanSize(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes < 0) return '—';
  const units = ['B', 'kB', 'MB', 'GB'] as const;
  let value = bytes;
  let idx = 0;
  while (value >= 1024 && idx < units.length - 1) {
    value /= 1024;
    idx += 1;
  }
  return `${value.toFixed(idx === 0 ? 0 : 2)} ${units[idx] ?? 'B'}`;
}

/** Show first 8 and last 4 chars of a long digest — enough to recognize
 *  it without wrapping the table. sha256 is already short enough to show
 *  in full; only sha512/sha1 get trimmed. */
export function shortenDigest(hex: string): string {
  if (hex.length <= 64) return hex;
  return `${hex.slice(0, 8)}…${hex.slice(-4)}`;
}
